function fiboEvenSum(n) {
  const arr = [];
  var x = 0;
  var y = 1;

  for (let i = 0; i < n && y + x < n; i++) {
    var nextNum = x + y;
      arr.push(nextNum); 
      x = y;
      y = nextNum;
   
  }

const newArr = arr.filter(x => x % 2 == 0);
let result= newArr.reduce((x,y) => x + y);
 return result;
}

console.log(fiboEvenSum(1000));

/*
Project Euler: Problem 2: Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

*/
